"""Core layer: configuration, event log, session policy, controller, executor.

Qt-free.  The UI is a consumer of this layer, never a peer of it.
"""

from .batch_runner import BatchOutcome, BatchRunReport, BatchRunner, StepRecord
from .config import (
    APP_NAME,
    DATA_DIR_ENV,
    DEFAULT_BATCH_SIZE,
    MAX_BATCH_SIZE,
    MIN_BATCH_SIZE,
    AppPaths,
    default_paths,
    placeholder_role_config,
)
from .config_exchange import (
    CONFIG_EXPORT_FORMAT,
    CONFIG_EXPORT_VERSION,
    MAX_EXPORT_BYTES,
    REDACTED_VALUE,
    ConfigExchangeError,
    ExportInput,
    apply_import,
    build_export,
    read_export,
    validate_export,
    write_export,
)
from .controller import ControlOutcome, ControlResult, PipelineController
from .diagnostics import (
    DriverDiagnostics,
    WorkspaceReadiness,
    collect_diagnostics,
    collect_driver_diagnostics,
    format_diagnostics,
    format_workspace_readiness,
    workspace_readiness_for,
)
from .events import EventLog, Listener, LogRecord, NullEventLog
from .executor import (
    AUDITOR_ROLE,
    DEFAULT_TASK_ROLE,
    ExecutionOutcome,
    ExecutionReport,
    Executor,
    FINAL_AUDITOR_ROLE,
    FinalAuditOutcome,
    FinalAuditReport,
    MAX_AUDIT_ROUNDS,
    MAX_NEXT_BATCH_SIZE,
    MIN_NEXT_BATCH_SIZE,
    ORCHESTRATOR_ROLE,
    PlanOutcome,
    PlanReport,
    StartNextBatchOutcome,
    StartNextBatchReport,
    TaskNextAction,
    TaskSpec,
    next_task_action,
)
from .final_audit_parser import (
    FINAL_AUDIT_ENVELOPE_END,
    FINAL_AUDIT_ENVELOPE_START,
    FinalAuditParseError,
    parse_final_audit,
)
from .hermes_profiles import (
    ProfileDiscoveryResult,
    discover_profiles,
    parse_profile_list,
    profile_roots,
)
from .plan_packet import PLANNING_OUTPUT_SCHEMA, render_planning_prompt
from .plan_parser import (
    PLAN_ENVELOPE_END,
    PLAN_ENVELOPE_START,
    PlanParseError,
    parse_batch_plan,
)
from .repo_fingerprint import (
    GIT_TIMEOUT_S,
    RepoFingerprint,
    capture_repo_fingerprint,
    fingerprints_equal,
)
from .session_manager import (
    ROLE_SESSION_POLICY_DESCRIPTION,
    SessionAction,
    SessionDecision,
    SessionManager,
    decide_session_action,
)
from .verdict_parser import (
    AUDIT_ENVELOPE_END,
    AUDIT_ENVELOPE_START,
    VerdictParseError,
    parse_audit_verdict,
)

__all__ = [
    "APP_NAME",
    "DATA_DIR_ENV",
    "AUDIT_ENVELOPE_END",
    "AUDIT_ENVELOPE_START",
    "AUDITOR_ROLE",
    "AppPaths",
    "BatchOutcome",
    "BatchRunReport",
    "BatchRunner",
    "CONFIG_EXPORT_FORMAT",
    "CONFIG_EXPORT_VERSION",
    "ConfigExchangeError",
    "ControlOutcome",
    "ControlResult",
    "DriverDiagnostics",
    "WorkspaceReadiness",
    "collect_diagnostics",
    "collect_driver_diagnostics",
    "format_diagnostics",
    "format_workspace_readiness",
    "workspace_readiness_for",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_TASK_ROLE",
    "EventLog",
    "ExecutionOutcome",
    "ExecutionReport",
    "Executor",
    "ExportInput",
    "FINAL_AUDITOR_ROLE",
    "FINAL_AUDIT_ENVELOPE_END",
    "FINAL_AUDIT_ENVELOPE_START",
    "FinalAuditOutcome",
    "FinalAuditParseError",
    "FinalAuditReport",
    "GIT_TIMEOUT_S",
    "Listener",
    "LogRecord",
    "MAX_AUDIT_ROUNDS",
    "MAX_BATCH_SIZE",
    "MAX_EXPORT_BYTES",
    "MAX_NEXT_BATCH_SIZE",
    "MIN_BATCH_SIZE",
    "MIN_NEXT_BATCH_SIZE",
    "NullEventLog",
    "ORCHESTRATOR_ROLE",
    "PLAN_ENVELOPE_END",
    "PLAN_ENVELOPE_START",
    "PipelineController",
    "PlanOutcome",
    "PlanParseError",
    "PlanReport",
    "PLANNING_OUTPUT_SCHEMA",
    "ProfileDiscoveryResult",
    "REDACTED_VALUE",
    "ROLE_SESSION_POLICY_DESCRIPTION",
    "RepoFingerprint",
    "SessionAction",
    "SessionDecision",
    "SessionManager",
    "StartNextBatchOutcome",
    "StartNextBatchReport",
    "StepRecord",
    "TaskNextAction",
    "TaskSpec",
    "VerdictParseError",
    "apply_import",
    "build_export",
    "capture_repo_fingerprint",
    "decide_session_action",
    "default_paths",
    "discover_profiles",
    "fingerprints_equal",
    "next_task_action",
    "parse_audit_verdict",
    "parse_batch_plan",
    "parse_final_audit",
    "parse_profile_list",
    "placeholder_role_config",
    "profile_roots",
    "read_export",
    "render_planning_prompt",
    "validate_export",
    "write_export",
]